# Generated by Django 4.2.4 on 2023-08-17 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_delete_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="number_likes",
            new_name="likes",
        ),
    ]
