# Generated by Django 4.2.4 on 2023-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_number_likes_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
